export const RECIPE_DESCRIPTION_MOCKS = [
	"Indulge in this nutrient-packed dish that balances lean protein and healthy fats, providing you with a delicious meal that nourishes your body and keeps you full for hours.",
	"This hearty and wholesome recipe is perfect for those looking to enjoy a quick meal that's both flavorful and packed with essential nutrients to fuel your day.",
	"Prepare a flavorful dish that's not only easy to make but also incredibly nutritious, offering the perfect balance of taste and health in every bite.",
	"Treat yourself to this protein-rich recipe that combines fresh ingredients and healthy fats to create a meal that’s both satisfying and full of flavor.",
	"Discover the simplicity of healthy cooking with this easy-to-follow recipe, packed with vibrant flavors and nutrients that will keep you feeling energized.",
	"Fuel your day with this quick and healthy recipe, designed to give you the right balance of protein, fat, and fiber, all wrapped in delicious taste.",
	"This recipe is your go-to for a balanced meal that’s quick to prepare, loaded with essential nutrients, and bursting with flavors that will delight your taste buds.",
	"Enjoy this light yet filling meal that’s perfect for any time of day, providing a delicious mix of protein and fiber to keep you full and satisfied.",
	"Cook up this wholesome recipe that’s rich in nutrients, low in carbs, and packed with flavors that are sure to become a favorite in your household.",
	"Packed with protein, healthy fats, and a range of essential vitamins, this recipe is the perfect way to nourish your body while enjoying a flavorful meal.",
	"With just a few simple ingredients, you can create a delicious and nutritious meal that offers the perfect balance of health and flavor in every bite.",
	"This recipe delivers a burst of flavor and nutrition in one easy-to-make dish, combining lean proteins, healthy fats, and fresh ingredients to create a meal that supports your health goals.",
	"Enjoy the ultimate combination of flavor and nutrition with this dish, designed to deliver a balance of essential nutrients while keeping things simple and delicious.",
	"Whip up a delicious and nutritious meal with this recipe, packed with all the essential nutrients your body needs to stay fueled and healthy.",
	"This easy-to-prepare dish is perfect for those busy days when you want something healthy, tasty, and full of nutrients without spending too much time in the kitchen.",
	"A delicious blend of healthy ingredients comes together in this recipe to create a dish that’s full of flavor, protein, and essential nutrients to keep you going strong.",
	"Savor every bite of this delicious and nutritious recipe, packed with lean protein, fresh vegetables, and healthy fats that make it a complete, satisfying meal.",
	"This recipe offers a perfect blend of simplicity, nutrition, and taste, making it an ideal choice for those looking to enjoy a balanced meal with minimal effort.",
	"Full of fresh ingredients and rich in essential nutrients, this recipe is both quick to prepare and packed with flavor, making it a great option for any meal.",
	"Enjoy the perfect combination of flavor, nutrition, and ease with this recipe, offering a healthy balance of protein and fats that’s both satisfying and delicious.",
];
